# ETİ MADEN PYTHON EĞİTİMİ - GÜN 2
## Operatörler, Veri Yapıları ve Spekt Kontrol Sistemi

**GERÇEK ETİ MADEN ÜRÜN SPEKTLERİ KULLANILMIŞTIR**

### Veri Kaynakları:
- **Etibor-48**: [PDF](https://www.etiproducts.com/wp-content/uploads/2018/01/6-2017-Etibor_48.pdf)
- **Kolemanit**: [PDF](https://www.etimineusa.com/wp-content/uploads/2020/01/TDS-of-Ground-Colemanite-M-2018-specs.pdf)
- **Borik Asit**: [PDF](https://www.etiproducts.com/wp-content/uploads/2019/05/Etiproducts-SDS-2019.02-Refined-Boric-Acid-English.pdf)

---


## BÖLÜM 1: LİSTELER VE TUPLE YAPILARI
### 1.1 Liste Oluşturma ve Temel İşlemler

In [16]:
vardiya_uretim = [1250, 1180, 1340]
print(f"Vardiya üretim listesi: {vardiya_uretim}")

Vardiya üretim listesi: [1250, 1180, 1340]


In [17]:
# append() methodu listenin sonuna eleman eklemeye yarar
vardiya_uretim.append(1290)
print(f'Ek vardiya eklendi:{vardiya_uretim}')

Ek vardiya eklendi:[1250, 1180, 1340, 1290]


In [18]:
#extend() methodu birden fazla veri eklemene yarar
hafta_sonu_uretim = [1100, 1050]
vardiya_uretim.extend(hafta_sonu_uretim)
print(f"Hafta Sonu Üretimi Eklendi: {vardiya_uretim}")

Hafta Sonu Üretimi Eklendi: [1250, 1180, 1340, 1290, 1100, 1050]


In [19]:
#pop() methodu listeden son veriyi otomatik olarak kaldırır
son_vardiya = vardiya_uretim.pop()
print(f"Son vardiya çıkarıldı: {son_vardiya}")
print(f"Güncel Liste: {vardiya_uretim}")

Son vardiya çıkarıldı: 1050
Güncel Liste: [1250, 1180, 1340, 1290, 1100]


# İndexleme ve Dilimleme

In [20]:
ilk_uc_vardiya = vardiya_uretim[:3] # [:3] :'nın soluna bir şey yazılmadığı vakit varsıyalan olarak en baştaki değeri alır
print(f"İlk 3 vardiya: {ilk_uc_vardiya}")

İlk 3 vardiya: [1250, 1180, 1340]


In [21]:
son_iki_vardiya = vardiya_uretim[4:]# [4:] :'nın sağ kısmı boş bırakıldığında varsayılan olarak en sonun indeks dahil alır
print(f"son_iki_vardiya: {son_iki_vardiya}")

son_iki_vardiya: [1100]


In [22]:
cift_vardiyalılar = vardiya_uretim[::2] # [::2] buradaki 2 değeri 2 şer 2 şer atlayarak gideceğini gösterir.
print(f"Çift vardiylaların üretimi: {cift_vardiyalılar}")

Çift vardiylaların üretimi: [1250, 1340, 1100]


# İstatiksel Özet

In [25]:
toplam = sum(vardiya_uretim)
ortalama = toplam / len(vardiya_uretim) # len() eleman sayısını verir
minimum = min(vardiya_uretim)
maximum = max(vardiya_uretim)

print(f"Toplam: {toplam} ton")
print(f"Ortalam: {ortalama} ton")
print(f"Minimum: {minimum} ton")
print(f"Maksimum: {maximum} ton")

Toplam: 6160 ton
Ortalam: 1232.0 ton
Minimum: 1100 ton
Maksimum: 1340 ton


# Sıralama

In [27]:
vardiya_kopya = vardiya_uretim.copy() # kopyasını aldık orjinalliği bozmamak için

vardiya_kopya.sort() # küçükten büyüğe doğru sıralar
print(f"Artan Sıralama: {vardiya_kopya}")


vardiya_kopya.sort(reverse=True) # büyükten küçüğe doğru sıralar
print(f"Azalan Sıralama: {vardiya_kopya}")

Artan Sıralama: [1100, 1180, 1250, 1290, 1340]
Azalan Sıralama: [1340, 1290, 1250, 1180, 1100]


### 1.2 Tuple Yapıları

tuple tipindeki listeler normal listelerle birebir aynı özelliklere sahipler iç içe listeleri birbirinden daha rahat okunabilir hale getirmek için kullanılır.

In [28]:
[[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [29]:
[(1,2,3),(4,5,6)]

[(1, 2, 3), (4, 5, 6)]

In [30]:
tesis_kordinatları = (39.3833, 27.2533)
print(f"Tesis koordinatları: {tesis_kordinatları}")
print(f"Enlem: {tesis_kordinatları[0]}, Boylam: {tesis_kordinatları[1]}")

Tesis koordinatları: (39.3833, 27.2533)
Enlem: 39.3833, Boylam: 27.2533


In [31]:
etibor48_spekt = (48.0, 49.35, 'B2O3', '%')

min_deger, max_deger, parametre, birim = etibor48_spekt

print(f"{parametre}: {min_deger}{birim} - {max_deger}{birim}")

B2O3: 48.0% - 49.35%


## BÖLÜM 3: SÖZLÜKLER VE KÜMELER
### 3.1 Sözlük Yapısı

In [32]:
kirici_1 = {
    'ekipman_id':'KRC-001',
    'tip':'Çeneli Kırıcı',
    'kapasite_ton_saat':150,
    'motor_gucu_kw':250,
    'sicaklik_C':65
}


print(f"ID: {kirici_1['ekipman_id']}")
print(f"Tip: {kirici_1['tip']}")
print(f"Kapasite: {kirici_1['kapasite_ton_saat']} ton saat")

ID: KRC-001
Tip: Çeneli Kırıcı
Kapasite: 150 ton saat


# Sözlük Methodları

In [35]:
liste_kirici1 = kirici_1.items()
print(liste_kirici1)

dict_items([('ekipman_id', 'KRC-001'), ('tip', 'Çeneli Kırıcı'), ('kapasite_ton_saat', 150), ('motor_gucu_kw', 250), ('sicaklik_C', 65)])


In [36]:
for key, value in liste_kirici1:
    print(f"Key:{key} -> value:{value}")

Key:ekipman_id -> value:KRC-001
Key:tip -> value:Çeneli Kırıcı
Key:kapasite_ton_saat -> value:150
Key:motor_gucu_kw -> value:250
Key:sicaklik_C -> value:65


In [37]:
print(f"Anahtarlar: {list(kirici_1.keys())}")
print(f"Değerler: {list(kirici_1.values())}")

Anahtarlar: ['ekipman_id', 'tip', 'kapasite_ton_saat', 'motor_gucu_kw', 'sicaklik_C']
Değerler: ['KRC-001', 'Çeneli Kırıcı', 150, 250, 65]


### 3.3 JSON Benzeri Veri Yapıları

In [39]:
tesis_ekipmanları = {
    'kiricilar': [
        {'ekipman_id':'KRC-001','tip':'Çeneli Kırıcı','kapasite_ton_saat':150,'motor_gucu_kw':250,'sicaklik_C':65,'durum':'Aktif'},
        {'ekipman_id':'KRC-002','tip':'Konik','kapasite_ton_saat':200,'motor_gucu_kw':300,'sicaklik_C':80,'durum':'Bakımda'}
    ],

    'elekler':[
        {'id':'ELK-001', 'goz_boyutu_mm':25, 'durum':'Aktif'}
    ]
}

In [40]:
print(f'TOPLAM Kırıcı: {len(tesis_ekipmanları['kiricilar'])}')
for kirici in tesis_ekipmanları['kiricilar']:
    if kirici['durum'] == 'Aktif':
        print(f"Aktif: {kirici['ekipman_id']} {kirici['tip']}")


TOPLAM Kırıcı: 2
Aktif: KRC-001 Çeneli Kırıcı


In [42]:
urun_spektleri = {
    'Etibor-48':{
        'B2O3':{'min':48.0, 'max':49.35, 'birim':'%'},
        "Na2O": {"min": 21.37, "max": 21.95, "birim": "%"},
        "SO4": {"min": None, "max": 135, "birim": "ppm"},
        "Fe": {"min": None, "max": 3, "birim": "ppm"}
    },
    'Borik Asit': {
        "H3BO3": {"min": 99.9, "max": None, "birim": "%"},
        "B2O3": {"min": 56.25, "max": None, "birim": "%"}
    },
    'Kolemanit':{
        "B2O3": {"min": 42.0, "max": 50.9, "birim": "%"},
        "CaO": {"min": 24.0, "max": 27.2, "birim": "%"}
    }
}



list(urun_spektleri.items())

[('Etibor-48',
  {'B2O3': {'min': 48.0, 'max': 49.35, 'birim': '%'},
   'Na2O': {'min': 21.37, 'max': 21.95, 'birim': '%'},
   'SO4': {'min': None, 'max': 135, 'birim': 'ppm'},
   'Fe': {'min': None, 'max': 3, 'birim': 'ppm'}}),
 ('Borik Asit',
  {'H3BO3': {'min': 99.9, 'max': None, 'birim': '%'},
   'B2O3': {'min': 56.25, 'max': None, 'birim': '%'}}),
 ('Kolemanit',
  {'B2O3': {'min': 42.0, 'max': 50.9, 'birim': '%'},
   'CaO': {'min': 24.0, 'max': 27.2, 'birim': '%'}})]

In [43]:
for urun, parametreler in urun_spektleri.items():
    print(f"\n{urun}")
    for param, degerler in parametreler.items():
        min_v = degerler['min'] if degerler['min'] else '-'
        max_v = degerler['max'] if degerler['max'] else '-'
        print(f" {param}: {min_v} - {max_v} {degerler['birim']}")


Etibor-48
 B2O3: 48.0 - 49.35 %
 Na2O: 21.37 - 21.95 %
 SO4: - - 135 ppm
 Fe: - - 3 ppm

Borik Asit
 H3BO3: 99.9 - - %
 B2O3: 56.25 - - %

Kolemanit
 B2O3: 42.0 - 50.9 %
 CaO: 24.0 - 27.2 %


## BÖLÜM 5: SPEKT KONTROL SİSTEMİ
### 5.1 Etibor-48 Kalite Kontrolü

In [52]:
urun_adi = "Etibor-48"
olcum_b2o3 = 48.75
olcum_na2o = 21.50
olcum_so4 = 120
olcum_fe = 2

print(f"Ürün: {urun_adi}")
print(f"B₂O₃: {olcum_b2o3}%")
print(f"Na₂O: {olcum_na2o}%")
print(f"SO₄: {olcum_so4} ppm")
print(f"Fe: {olcum_fe} ppm")

Ürün: Etibor-48
B₂O₃: 48.75%
Na₂O: 21.5%
SO₄: 120 ppm
Fe: 2 ppm


In [53]:
urun_spektleri

{'Etibor-48': {'B2O3': {'min': 48.0, 'max': 49.35, 'birim': '%'},
  'Na2O': {'min': 21.37, 'max': 21.95, 'birim': '%'},
  'SO4': {'min': None, 'max': 135, 'birim': 'ppm'},
  'Fe': {'min': None, 'max': 3, 'birim': 'ppm'}},
 'Borik Asit': {'H3BO3': {'min': 99.9, 'max': None, 'birim': '%'},
  'B2O3': {'min': 56.25, 'max': None, 'birim': '%'}},
 'Kolemanit': {'B2O3': {'min': 42.0, 'max': 50.9, 'birim': '%'},
  'CaO': {'min': 24.0, 'max': 27.2, 'birim': '%'}}}

In [55]:
spekt_b2o3 = urun_spektleri['Etibor-48']['B2O3']
b2o3_uygun = (olcum_b2o3 >= spekt_b2o3['min']) and (olcum_b2o3 <= spekt_b2o3['max'])

print(f"\nB₂O₃ Kontrolü:")
print(f"  Spekt: {spekt_b2o3['min']}-{spekt_b2o3['max']}{spekt_b2o3['birim']}")
print(f"  Ölçüm: {olcum_b2o3}{spekt_b2o3['birim']}")
print(f"  Durum: {'✓ UYGUN' if b2o3_uygun else '✗ UYGUN DEĞİL'}")


B₂O₃ Kontrolü:
  Spekt: 48.0-49.35%
  Ölçüm: 48.75%
  Durum: ✓ UYGUN


In [56]:
# Diğer Parametreler
spekt_na2o = urun_spektleri[urun_adi]["Na2O"]
na2o_uygun = (olcum_na2o >= spekt_na2o["min"]) and (olcum_na2o <= spekt_na2o["max"])

spekt_so4 = urun_spektleri[urun_adi]["SO4"]
so4_uygun = olcum_so4 <= spekt_so4["max"]

spekt_fe = urun_spektleri[urun_adi]["Fe"]
fe_uygun = olcum_fe <= spekt_fe["max"]

print(f"Na₂O: {'✓' if na2o_uygun else '✗'}")
print(f"SO₄: {'✓' if so4_uygun else '✗'}")
print(f"Fe: {'✓' if fe_uygun else '✗'}")

tum_uygun = b2o3_uygun and na2o_uygun and so4_uygun and fe_uygun
print(f"\n{'='*40}")
print(f"SONUÇ: {'✓ TÜM TESTLER UYGUN' if tum_uygun else '✗ UYGUNSUZLUK'}")
print(f"{'='*40}")

Na₂O: ✓
SO₄: ✓
Fe: ✓

SONUÇ: ✓ TÜM TESTLER UYGUN


# Nem Yüzdesi Hesabı
Bir maden örneğinin yaş ağırlığı 1000 gram, kuru ağırlığı ise 850 gramdır.

Python kullanarak nem yüzdesini hesaplayınız.
İpucu: Nem yüzdesi formülü:

Nem (%) = ((yaş ağırlık - kuru ağırlık) / yaş ağırlık) * 100


# Alıştırma 1 
# Motor Sıcaklığı 85 C derece olsun ve sizden bunu K cinsine dönüşüm yapılması istenip yazdırılmak isteniyor. 273.15 derece eklenmesi lazım
# Hem Celcius C hem de K Santigrad yazdıracaksınız

In [ ]:

urun_spektleri = {
    'Etibor-48':{
        'B2O3':{'min':48.0, 'max':49.35, 'birim':'%'},
        "Na2O": {"min": 21.37, "max": 21.95, "birim": "%"},
        "SO4": {"min": None, "max": 135, "birim": "ppm"},
        "Fe": {"min": None, "max": 3, "birim": "ppm"}
    },
    'Borik Asit': {
        "H3BO3": {"min": 99.9, "max": None, "birim": "%"},
        "B2O3": {"min": 56.25, "max": None, "birim": "%"}
    },
    'Kolemanit':{
        "B2O3": {"min": 42.0, "max": 50.9, "birim": "%"},
        "CaO": {"min": 24.0, "max": 27.2, "birim": "%"}
    }
}

# Alıştırma 2 
-> borik asit ölçümü yapıldı ve bunun 99.62 olduğu ölçüldü. bunun H3BO3 değerine göre eğer ölçüm urun spektinden büyükse uygundur değilse uygun değildir bunun raporunu yazdırınız.

In [ ]:
borik_asit_olcumu = 99.62
H3BO3_referans_deger = urun_spektleri['Borik Asit']['H3BO3']['min']
print(f"{'Uygun' if borik_asit_olcumu <= H3BO3_referans_deger else 'Uygun Değil'}")


Uygun


# Alıştırma 3

Pazartesi 1250 ton üretildi

Salı 1180 ton üretildi

Çarşamba 1340 ton üretildi

Perşembe 1290 ton üretildi

Cuma 1100 ton üretildi

Cumartesi 1050 ton üretildi

Pazar 1420 ton üretildi

Bunu liste olarak yazın sonrasında 1200 hedefini tutturanların oranını raporlayın.

sadece hedefi tuturanların len() methodu ile listenin eleman sayısını alıcaksın ve sum() toplam üretilen tonu alacaksın

# Bor Üretim Listesi Yönetimi

Bir bor madeni işletmesinde haftalık üretim miktarları (ton cinsinden) oluşturun. 

madde 1-) 7 elemanlı bir liste olucak üretim miktarları sırasıyla 1200, 1500, 1100, 1400, 1600, 1900,2000 ton olucak

madde 2-) Hafta içi üretimleri ayrı değişkene hafta_ici_uretim hafta sonu üretimlerini ayrı bir değişkene alalım hata_sonu_uretim. Bunun için dilimleme yapmalısınız

madde 3-) hafta içi üretimlerinin ortalaması almalısınız ve hafta sonu üretimlerinden ortamalasını almalısınız. sum() methoduyla toplama len() methoduyla eleman sayısını aldıktan sonra birbirine oranlayıp ortalamayı bulmalısınız.

madde 4-) ortalama 1600 tonun altına kalan değerler üretim yetersiz üstünde kalan değer için ise yeterli üretim diye rapor yazdırın.
tek satır if else çalıştırın.
örnek kod: print(f"SONUÇ: {'✓ TÜM TESTLER UYGUN' if tum_uygun else '✗ UYGUNSUZLUK'}")


In [6]:
vardiya_uretim = [1200, 1500, 1100, 1400, 1600, 1900,2000]

hafta_ici_uretim = vardiya_uretim[:]
hafta_sonu_uretim = vardiya_uretim[-2:]

hafta_ici_ortalama_uretim = sum(hafta_ici_uretim) / len(hafta_ici_uretim)
hafta_sonu_ortalama_uretim = sum(hafta_sonu_uretim) / len(hafta_sonu_uretim)

esik_degeri = 1600

print(f"Hafta İçi Üretim -> {'Yeterli Üretim' if hafta_ici_ortalama_uretim >= esik_degeri else 'Yetersiz Üretim'}")

print(f"Hafta Sonu Üretim -> {'Yeterli Üretim' if hafta_sonu_ortalama_uretim >= esik_degeri else 'Yetersiz Üretim'}")



Hafta İçi Üretim -> Yetersiz Üretim
Hafta Sonu Üretim -> Yeterli Üretim


# Ürün Spektleri Sözlüğü

Etibor-48: B2O3 (%48–49.35), Na2O (%21.37–21.95), SO4 (max 135 ppm), Fe (max 3 ppm)

Borik Asit: H3BO3 (min %99.9), B2O3 (min %56.25)
 
Kolemanit: B2O3 (%42–50.9), CaO (%24–27.2)

bu jsonu devam ettirin.

In [7]:
urun_spektleri = {
    "Etibor-48": {
        "B2O3": {"min": 48.0, "max": 49.35, "birim": "%"},
        "Na2O": {"min": 21.37, "max": 21.95, "birim": "%"},
        "SO4": {"min": None, "max": 135, "birim": "ppm"},
        "Fe": {"min": None, "max": 3, "birim": "   ppm"}
    },
    "Borik Asit": {
        "H3BO3": {"min": 99.9, "max": None, "birim": "%"},
        "B2O3": {"min": 56.25, "max": None, "birim": "%"}
    },
    "Kolemanit": {
        "B2O3": {"min": 42.0, "max": 50.9, "birim": "%"},
        "CaO": {"min": 24.0, "max": 27.2, "birim": "%"}
    }
}






# Ürün Spektleri Raporu
Görev:  
Her ürünün tüm parametrelerini (örneğin B2O3, Na2O, SO4, Fe) ekrana yazdıran bir Python programı yazınız.

Eğer min değeri yoksa (None), ekranda "-" olarak gösteriniz.

Eğer max değeri yoksa (None), ekranda "-" olarak gösteriniz.

örnek çıktı: 

Etibor-48:

  B2O3: 48.0 - 49.35 %

  Na2O: 21.37 - 21.95 %

  SO4: - - 135 ppm
  
  Fe: - - 3 ppm

İpucu:

        dict.items() ile hem ürün adını hem de parametrelerini dolaşabilirsiniz.

        İç içe for döngüsü kullanarak her parametreyi ayrı ayrı yazdırabilirsiniz.

        if koşulu ile None değerlerini kontrol edip yerine "-" koyabilirsiniz.

In [9]:
list(urun_spektleri.items())

[('Etibor-48',
  {'B2O3': {'min': 48.0, 'max': 49.35, 'birim': '%'},
   'Na2O': {'min': 21.37, 'max': 21.95, 'birim': '%'},
   'SO4': {'min': None, 'max': 135, 'birim': 'ppm'},
   'Fe': {'min': None, 'max': 3, 'birim': '   ppm'}}),
 ('Borik Asit',
  {'H3BO3': {'min': 99.9, 'max': None, 'birim': '%'},
   'B2O3': {'min': 56.25, 'max': None, 'birim': '%'}}),
 ('Kolemanit',
  {'B2O3': {'min': 42.0, 'max': 50.9, 'birim': '%'},
   'CaO': {'min': 24.0, 'max': 27.2, 'birim': '%'}})]

In [15]:
degisken = 'Deger'
'değer var 'if degisken else 'değer yok'

'değer var '

In [ ]:
for urun, parametreler in urun_spektleri.items():
        print(f"\n{urun}:")
        for param, degerler in parametreler.items():

                min_v = degerler['min'] if degerler['min'] else '-'
                max_v = degerler['max'] if degerler['max'] else '-'
                print(param, min_v, max_v, degerler['birim'])     


Etibor-48:
B2O3 48.0 49.35 %
Na2O 21.37 21.95 %
SO4 - 135 ppm
Fe - 3    ppm

Borik Asit:
H3BO3 99.9 - %
B2O3 56.25 - %

Kolemanit:
B2O3 42.0 50.9 %
CaO 24.0 27.2 %


In [16]:
urun_adi = "Etibor-48"
olcum_b2o3 = 48.75
olcum_na2o = 21.50
olcum_so4 = 120
olcum_fe = 2

print(f"Ürün: {urun_adi}")
print(f"B₂O₃: {olcum_b2o3}%")
print(f"Na₂O: {olcum_na2o}%")
print(f"SO₄: {olcum_so4} ppm")
print(f"Fe: {olcum_fe} ppm")

Ürün: Etibor-48
B₂O₃: 48.75%
Na₂O: 21.5%
SO₄: 120 ppm
Fe: 2 ppm


B₂O₃ Kontrolü
Eti Maden ürün spektlerinde her parametrenin min ve max değerleri tanımlıdır.
Bir ürün için yapılan ölçümün bu aralıkta olup olmadığını kontrol eden bir Python programı yazınız.

Görevler:

urun_spektleri sözlüğünden seçilen ürünün B₂O₃ değerlerini alın.

Ölçüm değerini (olcum_b2o3) spekt aralığına göre kontrol edin.

Eğer ölçüm aralıkta ise "✓ UYGUN", değilse "✗ UYGUN DEĞİL" yazdırın.

Ölçüm ile min ve max değerler arasındaki hata payını (%) hesaplayın.


B₂O₃ Kontrolü:
  Spekt: 48.0-49.35 %

  Ölçüm: 49.0 %

  Durum: ✓ UYGUN

  Min hata payı: 2.08%
  
  Max hata payı: 0.71%


In [ ]:
min =urun_spektleri['Etibor-48']['B2O3']['min']
max= urun_spektleri['Etibor-48']['B2O3']['max']
olcum_b2o3 = 48.75
print(min,max)

48.0 49.35
